export const ingredients = [
  { index: 1, value: 50, label: "Biotyna (μg)" },
  { index: 2, value: 800, label: "Chlor (mg)" },
  { index: 3, value: 40, label: "Chrom (μg)" },
  { index: 4, value: 10, label: "Cynk (mg)" },
  { index: 5, value: 3.5, label: "Fluor (mg)" },
  { index: 6, value: 700, label: "Fosfor (mg)" },
  { index: 7, value: 150, label: "Jod (μg)" },
  { index: 8, value: 200, label: "Kwas foliowy (μg)" },
  { index: 9, value: 6, label: "Kwas pantotenowy (mg)" },
  { index: 10, value: 375, label: "Magnez (mg)" },
  { index: 11, value: 2, label: "Mangan (mg)" },
  { index: 12, value: 1, label: "Miedź (mg)" },
  { index: 13, value: 50, label: "Molibden (μg)" },
  { index: 14, value: 16, label: "Niacyna (mg)" },
  { index: 15, value: 2000, label: "Potas (mg)" },
  { index: 16, value: 1.4, label: "Ryboflawina (mg)" },
  { index: 17, value: 55, label: "Selen (μg)" },
  { index: 18, value: 1.1, label: "Tiamina (mg)" },
  { index: 19, value: 800, label: "Wapń (mg)" },
  { index: 20, value: 800, label: "Witamina A (μg)" },
  { index: 21, value: 2.5, label: "Witamina B12 (μg)" },
  { index: 22, value: 1.4, label: "Witamina B6 (mg)" },
  { index: 23, value: 80, label: "Witamina C (mg)" },
  { index: 24, value: 5, label: "Witamina D (μg)" },
  { index: 25, value: 12, label: "Witamina E (mg)" },
  { index: 26, value: 75, label: "Witamina K (μg)" },
  { index: 27, value: 14, label: "Żelazo (mg)" }
];
